### PR TITLE
Fix for Issue 34

### PR DESCRIPTION
**Pull request by jeff2001**

### CODE REVIEW

**Comment by zionyx** [comment]
Thanks, i merged https://github.com/jeff2001/jenkins-tray/commit/18d2844b2f612d02d43b084b897e9dc6c6629f71. Leaving the other commit as i'll release 1.0.2 real soon.

Thank you for your contribution. Really appreciated.

**Comment by zionyx** [comment]
Work progress is tracked here: https://github.com/zionyx/jenkins-tray/issues/34

**Comment by jeff2001** [comment]
Thanks so much.

**Comment by zionyx** [comment]
No no, thank you. :+1:

**Pull request closed without merging**
