### PR TITLE
Update job detection to support using a view to monitor jenkins activ…

### PR DESCRIPTION
**Pull request by snowman78**
…ity.

When using cloudbees folders plugin the default url does not show jobs
within folders.   By creating a view and using that URL for the server we
can now monitor jobs within the folders using the tray app

### CODE REVIEW

**Comment by zionyx** [comment]
Thanks @snowman78 for your PR.

I tested it and i can now monitor folders. What about all projects within the folder? Have you thought about that?

As a user, i expect jenkins tray to be able to show all the projects in the folder, not just the folder itself. I think this is a much broader feature than it seems, IMHO. So i don't think selecting nodes with ``*/job`` would do the job.

Don't you think so?

**Comment by snowman78** [comment]
The main intent of the fix is to use a view URL for monitoring. eg.  http://jenkins/view/someview

The returned XML from this API is different than the root api.   The additional benefit gained is that I can now configure a view to recurse into subfolders and have access to monitor those jobs contained within the folders

**Comment by zionyx** [comment]
That's an interesting way of using it.

Perhaps can you also update the ``URL:`` field to show a tooltip or something, that Jenkins View and Folder are also supported?

So it won't become a hidden feature, and can be adapted by more users.

**Comment by zionyx** [comment]
Frankly speaking, i have been trying to implement #60 due to #57 is a much larger feature. I use Jenkins URL to get to the API Token of the user by appending ``me/configure`` to form the link. For instance, ``http://jenkins/me/configure``.

This PR will definitely block or make it more complex, because the Jenkins URL is no longer the root URL of Jenkins, but it can be any view / folder of any Jenkins instance.

**Comment by snowman78** [comment]
I have re-worked the change and the latest update supports using the root url to get folder and view content. It is no longer necessary to use a view to get folders. It will recursively traverse through folders to find all jobs on the server and presenting a unique list.

**Comment by zionyx** [comment]
Thanks, i'll get back to you soon. Just finished with v1.0.4 release.

**Comment by zionyx** [comment]
I tried the codes. Pretty slick recursive loop for folders. It should be used as the base functionality when looping for projects on Jenkins. :+1:

**Comment by zionyx** [comment]
Thank you @snowman78 for the PR. Very much appreciated.

**Pull request merged**
