### PR TITLE
Refactor to JenkinsTray

### PR DESCRIPTION
**Pull request by jeff2001**
Hi, I have done a refactor from Hudson to Jenkins.
Let me know if this is pull request is what you were thinking and works for you.
Thanks

### CODE REVIEW

**Comment by zionyx** [comment]
Thanks alot. I was thinking about refactoring it to just JenkinsTray so it
matches the project name. Removing the word Tracker saves some spaces too.

BR
Lee

**Comment by jeff2001** [comment]
Updated to remove Tracker from the name

**Comment by zionyx** [comment]
Thanks alot @jeff2001. I squashed all your commit into 1 and added a minor touch up before merging to master. Great work.

Are you ready for the next assignment? :smile:

**Comment by jeff2001** [comment]
Pleasure, fire away

**Comment by zionyx** [comment]
@jeff2001, please see https://github.com/zionyx/jenkins-tray/issues/43

**Pull request closed without merging**
