### PR TITLE
#22 Show tooltip "No projects are monitored." instead of "All builds …

### PR DESCRIPTION
**Pull request by BrandonHuber**
…are good." when there are no projects being monitored

Thought I'd give this bug a try. Is this close to what you had in mind?

### CODE REVIEW

**Comment by zionyx** [comment]
Hey @BrandonHuber, thank you for the PR! :+1: 

I reviewed it and had some comments. Do you agree with them? Let me know. Thanks.

**Comment by BrandonHuber** [comment]
Thanks for the quick reply! Good comments. I've updated the code based on your feedback.

**Comment by zionyx** [comment]
Sorry for the late reply.

Looks good, except for the pop up message, which is a little casual. Sounds like `Come get some!` from Duke Nukem. I'll get back to you after consulting my technical writer.

**Comment by zionyx** [comment]
Hi @BrandonHuber, sorry for the late reply, was really busy with work.

I think your initial text, "No project monitored." is short and simple. If you can help push another commit, that will be great. Then i'll just merge everything in and close this PR.

Thank you for your help.

**Comment by zionyx** [comment]
I merged your change to master. I also took the liberty to reuse your initial text as the tooltip, which is simple. Nothing beats simplicity.

I hope the delay does not stop you from contributing. Thanks @BrandonHuber! :+1:

**Comment by BrandonHuber** [comment]
Looks good to me, thanks! I think I like the first version better as well. For a tooltip it's probably more useful just to say what the state is, rather than try to give advice.

**Pull request merged**
